### ISSUE TITLE
Collection and Schema

### ISSUE THREAD

**Issue by alienbyday** [OrigenStudio/vulcan-files#2]
Hi, I've been trying to implement Meteor-Files in to Vulcan for way too many nights. Your work is looking promising.

Is there any chance you'll be able to show me your collection and schema to get this working. I feel like you've changed a few things from the original file-scalar package that you've based you work on.

Thanks in advance.

**Comment by ochicf** [comment]
Hi @alienbyday,

sorry for the late response. We are currently thinking in how would be the best/easiest way to add a file field into a Vulcan schema.

Right now we are only using this package in one project and it is quite messy (it is not decoupled at all with many of the quirks and specifics of that project) and I think it wouldn’t be that helpful to show it to you as it is, so I’ll try to make a more simple version ASAP. I think tomorrow I’ll be able to take some time to do it.

By the way, we also have been struggling a lot with this issue and we are glad to see that someone else has an interest in it, since we’re really hoping to get some outer inputs and help.

**Comment by ochicf** [comment]
Hi @alienbyday,

I've prepared a first draft of the readme. It's still a WIP and surely there will be a lot of missing and not enough clear concepts or steps, so sorry in advance.

I've also prepared the package to be used with the latest version of Vulcan... and I've had to fix an [issue](https://github.com/VulcanJS/Vulcan/pull/1982) in order for it to work properly, so you might want to install Vulcan locally from our [fork](https://github.com/OrigenStudio/Vulcan/tree/fix/multiple-datatypes) and do the [Vulcanstagram example](https://github.com/OrigenStudio/vulcan-files#31-vulcanstagram) I've written.

Please do not hesitate to ask any question you might have or to point out any errors or problems you encounter.

Thanks!

**Comment by alienbyday** [comment]
Oh this is great. I've got a full week coming up to work on my project. I'll report back once I make some progress.

Thanks for you time.

**Comment by ochicf** [comment]
Hey @alienbyday,

We created a [project](https://github.com/OrigenStudio/vulcan-files-simple-example) with the example so it is easy to run it, and now the tutorial and its code is defined there as a [standalone package](https://github.com/OrigenStudio/vulcan-files-simple-example/tree/master/packages/example-instagram).

Hope you find it useful, and please do not hesitate to ask any question or make suggestions. We'd much appreciate the latter :)

**Comment by alienbyday** [comment]
That worked perfectly. There were two more NPM dependencies I had to add to my project Knox and GM. They're missing from your read me. Other than that it was easy to get running.

Thanks a lot you've saved me a ton of time
